#!/bin/bash

# Retrieve arguments
domain=$1
path=$2

sudo yunohost app checkurl $domain$path -a sickbeard
if [[ ! $? -eq 0 ]]; then
  exit 1
fi

# Set destinations
package_dest=/opt/yunohost/sickbeard
data_dest=/home/yunohost.app/sickbeard

# Make directories and set rights
sudo mkdir -p $package_dest
sudo mkdir -p $data_dest
sudo chmod 755 -R $package_dest

# Create user
sudo useradd -d /home/yunohost.app/sickbeard sickbeard

# Copy/Move files to right place
sudo cp -a ../sources/* $package_dest
sudo mv $package_dest/config.ini $data_dest
sudo mv $package_dest/data $data_dest/data

# Add new sickbeard service
sudo cp $package_dest/init.ubuntu /etc/init.d/sickbeard
sudo cp $package_dest/default.ubuntu /etc/default/sickbeard 
sudo chmod 777 /etc/init.d/sickbeard
sudo update-rc.d sickbeard defaults

# Remove trailing "/" for next commands
path=${path%/}

# Monitor service
sudo yunohost service add sickbeard

# Configure Nginx and generate SSOwat conf
sudo service sickbeard start
sudo sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/sickbeard.conf
sudo service nginx restart
echo $?
sudo yunohost app ssowatconf