#!/bin/bash

# Retrieve arguments
domain=$(sudo yunohost app setting sickrage domain)
path=$(sudo yunohost app setting sickrage path)

# Remove trailing "/" for next commands
path=${path%/}

# Configure Nginx and reload
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/sickrage.conf
sudo service nginx reload

