#!/bin/bash

# Stop SickRage service
sudo service sickrage stop

# Upgrade SickRage from official repository
sudo cd /opt/yunohost/sickrage
sudo git pull

# Restore rights on files
sudo chown -R sickrage /opt/yunohost/sickrage

# Restarting SickRage
sudo service sickrage start
